### ISSUE TITLE
Question: Secret key?

### ISSUE THREAD

**Issue by pavel-tashev** [prgayman/laravel-fcm#1]
In your documentation you say:

> In your .env file, add the server key and the secret key for the Firebase Cloud Messaging:

but you give example only with how to set up the server key:

`FIREBASE_SERVER_KEY=my_server_key`

There is nothing mentioned about the secret key. Is there something missed in the documentation? How to add the secret key?

**Comment by prgayman** [comment]
> In your documentation you say:
> 
> > In your .env file, add the server key and the secret key for the Firebase Cloud Messaging:
> 
> but you give example only with how to set up the server key:
> 
> `FIREBASE_SERVER_KEY=my_server_key`
> 
> There is nothing mentioned about the secret key. Is there something missed in the documentation? How to add the secret key?

I don't need the secret key only FIREBASE_SERVER_KEY

**Comment by prgayman** [comment]
FIREBASE_SERVER_KEY = Settings > Cloud Messaging >  Server key
